{% set version = '0.2.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-plogr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/plogr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/plogr/plogr_{{ version }}.tar.gz
  sha256: 0e63ba2e1f624005fe25c67cdd403636a912e063d682eca07f2f1d65e9870d29

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: Rcpp
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('plogr')"           # [not win]
    - "\"%R%\" -e \"library('plogr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/krlmlr/plogr#readme
  license: MIT + file LICENSE
  summary: ' A simple header-only logging library for C++. Add ''LinkingTo: plogr'' to ''DESCRIPTION'',
    and ''#include <plogr.h>'' in your C++ modules to use it.'

  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: plogr
# Title: The 'plog' C++ Logging Library
# Version: 0.2.0
# Date: 2018-03-24
# Authors@R: c( person("Kirill", "Muller", role = c("aut", "cre"), email = "krlmlr+r@mailbox.org"), person("Sergey", "Podobry", role = "cph", comment = "Author of the bundled plog library"))
# Description:  A simple header-only logging library for C++. Add 'LinkingTo: plogr' to 'DESCRIPTION', and '#include <plogr.h>' in your C++ modules to use it.
# Suggests: Rcpp
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# URL: https://github.com/krlmlr/plogr#readme
# BugReports: https://github.com/krlmlr/plogr/issues
# RoxygenNote: 6.0.1.9000
# NeedsCompilation: no
# Packaged: 2018-03-24 11:02:06 UTC; muelleki
# Author: Kirill Muller [aut, cre], Sergey Podobry [cph] (Author of the bundled plog library)
# Maintainer: Kirill Muller <krlmlr+r@mailbox.org>
# Repository: CRAN
# Date/Publication: 2018-03-25 15:25:27 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
