travis:
  secure:
    BINSTAR_TOKEN: Im5840dnYesos/03LxSsxMgVNUwVE/Nu/Yz2ALN3hafsujQRaf+25FY8+UMg5SCFpvMOM1F/OpmAni7MZ8mqHW7cCdJYsV/PwDUeyO3t9/GQk6BMOrGgyz3RNxAmnBeEnd4/ulmh71duqcrZj6Q+0SsuAQmv9wJObQMGsvl7baB67+Ln1aqXuk/Prmppik3b0bXBHDtOkUd6G81XyZndNv5777nshzn2cSpnK21c+o8/SkgqLPJMrWBXufCbCKT8TPN9luwTx3uUgNkD6t7/ep7KXZv62tO7ENMWHxnQtvo0dbfhxsmOlb04VbS0bs+iM9211cSq5gGdXaT1LyV5328qKAYPh9xjZfzzOZhfUc64hmieE4/X91Ox3NVktTESNI1bBy7PMabQKWxtarbcZjNw4x4rhAWbM2Q2bJb7/MTxwYYl91+f8xct733bgxxkIJbwkWbe9wmF9xcWh72Io7IdKyhsk6seLTrmxezR+8rAYG6PCoehZe5lVvmtJI23GfLTw9dPKkFQwKnGNqNwFoOYbyP9jyJYv2+DjbhMqx8nBaXh3rM6dBBL3Qewu9lvvR5Jqu2oAAWd3+HZiggk/C9lvefwqzgZmbvKfNL9qZAhK8FiKqT9aosS/b9zGMOVldhfIqtoO2O/PAJlVILdRELgBp7h2zxYV4kNCHvVsmU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
