travis:
  secure:
    BINSTAR_TOKEN: TrGyWq+Gk6pNfisFfBeP6oZNfDzSp2WwgD3CAJkqJykFVVzLZBxzDFqerTQMxl70G1jpFvdzDC0zdk6wAscBOYq11/Xu8WzQZLHEvMXS5vsKDT3jfZLgfN1g5DITPJRSvTahVd3GutKOuzLv45hOOP534GjA/iP41oFrHch8DkwKgB3n+udySG73lVUDcHRBIMFp9cmu+R9tqGQOHc8QKIDMsNCvoJrrSOXTA4FT5ZstddoNqsLE+GRla6NLtwq7c1noLi77WDIRNE1db9LlnIYsR5XwBqe6bBjxG6SEs2vpEu9BpUdT441SPFPFWSoxqs36jHwXWwRf5Z/iv9lPFM3RSo2VYTPgoYIAuJRp1WwGONiP9GZ88+PaJfsN5+wjxvB9CZ/GXbTWYon+nZ2TajHYJgXq/3d5/xkeub04QBIpMJvBzWBRjYITrEWjal0IKAVvEovbD1hIEQAXbXDn0DdktsmOvbzghvdQ/YAJkrDu8+DVCfagoLjODkNNtK/nnlkXkfoCwkV0Nqy36qkE2dhx12FR1oSzEmNb/8n5mumOZiDSoCjs5+j+NAJPXA8pF4NOsMrlqfJOSqARErqzQVw9vlI+PwplKbAbQD2wt4o46L5SHi3hGbRkRcgqNuZJfyqOl6xxq3Dm23IUmwVOy+Wk+e78Gs+xwem05aoXUwM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
